[package]
name = "morioka-eiki"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
morioka-eki-api = {path = "src/api"}